package com.oolonghoo.woosocial.sync;

public enum SyncMessageType {
    FRIEND_REQUEST,
    FRIEND_ACCEPT,
    FRIEND_DENY,
    FRIEND_REMOVE,
    PLAYER_ONLINE,
    PLAYER_OFFLINE,
    PLAYER_SWITCH_SERVER,
    NOTIFY_ONLINE,
    BLOCK_PLAYER,
    UNBLOCK_PLAYER,
    TELEPORT_REQUEST,
    TELEPORT_ACCEPT,
    TELEPORT_DENY,
    MAIL_NEW,
    MAIL_CLAIMED,
    MAIL_DELETED,
    
    RELATION_PROPOSE,
    RELATION_ACCEPT,
    RELATION_REMOVE,
    RELATION_INTIMACY_UPDATE,
    
    GIFT_SEND,
    GIFT_CLAIM,
    
    TRADE_REQUEST,
    TRADE_ACCEPT,
    TRADE_DENY,
    TRADE_CANCEL,
    TRADE_START,
    TRADE_UPDATE,
    TRADE_COMPLETE
}
